id = "basher"
name = "Basher"
version = "0.0.2"
schema_version = 1
description = "Bash-language-server support"
repository = "https://github.com/d1y/bash.zed"
authors = ["d1y <chenhonzhou@gmail.com>"]
themes = []
languages = ["languages/bash"]

[lib]
kind = "Rust"
version = "0.0.4"

[language_servers.bash-language-server]
language = "Shell Script"
